andromeda/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages
  resources :receivers

  get 'welcome/index'

  resources :messages
  authenticated :user do
    root to: 'messages#index', as: 'authenticated_root'
  end

  root to: 'welcome#index' 

end

andromeda/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

andromeda/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :receivers
end

andromeda/app/models/receiver.rb
class Receiver < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :messages
end

andromeda/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :messages
  has_many :receivers
end

andromeda/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

andromeda/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.where(user_id: current_user).order('created_at DESC')
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = current_user.messages.build
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = current_user.messages.build(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:subject, :message)
    end
end

andromeda/app/controllers/receivers_controller.rb
class ReceiversController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_receiver, only: [:show, :edit, :update, :destroy]

  # GET /receivers
  # GET /receivers.json
  def index
    @receivers = Receiver.where(user_id: current_user).order('created_at DESC')
  end

  # GET /receivers/1
  # GET /receivers/1.json
  def show
  end

  # GET /receivers/new
  def new
    @receiver = current_user.receivers.build
  end

  # GET /receivers/1/edit
  def edit
  end

  # POST /receivers
  # POST /receivers.json
  def create
    @receiver = current_user.receivers.build(receiver_params)

    respond_to do |format|
      if @receiver.save
        format.html { redirect_to @receiver, notice: 'Receiver was successfully created.' }
        format.json { render :show, status: :created, location: @receiver }
      else
        format.html { render :new }
        format.json { render json: @receiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receivers/1
  # PATCH/PUT /receivers/1.json
  def update
    respond_to do |format|
      if @receiver.update(receiver_params)
        format.html { redirect_to @receiver, notice: 'Receiver was successfully updated.' }
        format.json { render :show, status: :ok, location: @receiver }
      else
        format.html { render :edit }
        format.json { render json: @receiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receivers/1
  # DELETE /receivers/1.json
  def destroy
    @receiver.destroy
    respond_to do |format|
      format.html { redirect_to receivers_url, notice: 'Receiver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receiver
      @receiver = Receiver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receiver_params
      params.require(:receiver).permit(:name, :phone)
    end
end

andromeda/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  # GET /welcome
  # GET /welcome.json
  def index
  end

end

andromeda/app/helpers/application_helper.rb
module ApplicationHelper
end

andromeda/app/helpers/messages_helper.rb
module MessagesHelper
end

andromeda/app/helpers/receivers_helper.rb
module ReceiversHelper
end

andromeda/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Andromeda</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

andromeda/app/views/messages/_form.html.erb
<%= form_for(message) do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %>
    <%= f.text_field :subject %>
  </div>

  <div class="field">
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

andromeda/app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

andromeda/app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.subject %></td>
        <td><%= message.message %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

andromeda/app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

andromeda/app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @message.subject %>
</p>

<p>
  <strong>Message:</strong>
  <%= @message.message %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

andromeda/app/views/receivers/_form.html.erb
<%= form_for(receiver) do |f| %>
  <% if receiver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(receiver.errors.count, "error") %> prohibited this receiver from being saved:</h2>

      <ul>
      <% receiver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

andromeda/app/views/receivers/edit.html.erb
<h1>Editing Receiver</h1>

<%= render 'form', receiver: @receiver %>

<%= link_to 'Show', @receiver %> |
<%= link_to 'Back', receivers_path %>

andromeda/app/views/receivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Receivers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @receivers.each do |receiver| %>
      <tr>
        <td><%= receiver.name %></td>
        <td><%= receiver.phone %></td>
        <td><%= link_to 'Show', receiver %></td>
        <td><%= link_to 'Edit', edit_receiver_path(receiver) %></td>
        <td><%= link_to 'Destroy', receiver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receiver', new_receiver_path %>

andromeda/app/views/receivers/new.html.erb
<h1>New Receiver</h1>

<%= render 'form', receiver: @receiver %>

<%= link_to 'Back', receivers_path %>

andromeda/app/views/receivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @receiver.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @receiver.phone %>
</p>

<%= link_to 'Edit', edit_receiver_path(@receiver) %> |
<%= link_to 'Back', receivers_path %>

andromeda/app/views/welcome/index.html.erb
<h1>Welcome</h1>